import {
  ShieldCheck,
  Bug,
  HeartHandshake,
  Code2,
  User,
  Users,
  UserPlus,
  Church,
  BookOpenCheck,
  Dumbbell,
  HeartPulse,
  Wallet,
  Plane,
  GraduationCap,
  Briefcase,
  ShoppingCart,
  ChefHat,
  Salad,
  CalendarClock,
  FileStack,
  CalendarDays,
  Target,
  FolderKanban,
  Milestone,
  ClipboardList,
  Home,
  Car,
  Building2,
  Box,
  Sparkles,
  Sun,
  Moon,
  Coffee,
  Gift,
  Music,
  Camera,
  Palette,
  Star,
  Flag,
  MapPin,
  Clock,
  type LucideIcon,
} from "lucide-react";

/** Every icon a Life Category (or a merged calendar item's fallback) can
 * resolve to, keyed by the name stored in `life_areas.icon`. Extend this
 * list when adding a new curated option to `CategoryPicker`. */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  ShieldCheck,
  Bug,
  HeartHandshake,
  Code2,
  User,
  Users,
  UserPlus,
  Church,
  BookOpenCheck,
  Dumbbell,
  HeartPulse,
  Wallet,
  Plane,
  GraduationCap,
  Briefcase,
  ShoppingCart,
  ChefHat,
  Salad,
  CalendarClock,
  FileStack,
  CalendarDays,
  Target,
  FolderKanban,
  Milestone,
  ClipboardList,
  Home,
  Car,
  Building2,
  Box,
  Sparkles,
  Sun,
  Moon,
  Coffee,
  Gift,
  Music,
  Camera,
  Palette,
  Star,
  Flag,
  MapPin,
  Clock,
};

/** Curated subset offered to the user when picking an icon for a custom category. */
export const PICKABLE_ICON_NAMES = Object.keys(ICON_REGISTRY);

export function resolveIcon(name: string | null | undefined): LucideIcon {
  return (name && ICON_REGISTRY[name]) || CalendarDays;
}

/** A pleasant, distinct default palette offered in the color picker. */
export const CATEGORY_COLOR_SWATCHES = [
  "#3B82F6",
  "#8B5CF6",
  "#EC4899",
  "#F472B6",
  "#EF4444",
  "#F59E0B",
  "#FB923C",
  "#EAB308",
  "#84CC16",
  "#22C55E",
  "#10B981",
  "#14B8A6",
  "#0EA5E9",
  "#38BDF8",
  "#6366F1",
  "#A78BFA",
  "#818CF8",
  "#94A3B8",
  "#F87171",
  "#F97316",
];
